server:
  # 端口
  port: 8811
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/yjdata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxxx
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 20
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数 (20)
      maximum-pool-size: 30
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久，默认为1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间， 默认30000 (30秒)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      # connection-test-query: SELECT 1
  # Redis配置
#  redis:
#    # 超时时间
#    timeout: 10000ms
#    # 服务器地址
#    host: xxxxx
#    # 端口号
#    port: 6379
#    # 数据库(第几个)
#    database: 0
#    # 密码
#    # password:
#    lettuce:
#      pool:
#        # 最大连接数（默认8）
#        max-active: 1024
#        # 最大连接阻塞时间，默认-1
#        max-wait: 10000ms
#        # 最大空闲连接
#        max-idle: 200
#        # 最小空闲连接
#        min-idle: 5
  main:
    # 当遇到同名时，是否覆盖注册
    allow-bean-definition-overriding: true
# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.data.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.data.mapper: debug
# JWT
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 解密加密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（30*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer


